### ISSUE TITLE
Allow rearrangeable custom rate constants to be treated in an intuitive way by scientists

### ISSUE THREAD

**Issue by mattldawson** [NCAR/chemistry-cafe#16]
In the initial development effort to export MusicBox configuration files from the Chemistry Café, reactions with custom rate constant functions in CAM were re-arranged when possible to sets of standard reactions for use in MusicBox during the export process.

The scientists have expressed a need to continue to treat these reactions in the form they are currently in CAM (mathematically, and as a single reaction).

**Comment by K20shores** [comment]
Closing as this does not apply to the new version of chemistry cafe.
